/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShapesRouteImport } from './routes/shapes'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as IndexRouteImport } from './routes/index'

const ShapesRoute = ShapesRouteImport.update({
  id: '/shapes',
  path: '/shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/shapes': typeof ShapesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/shapes': typeof ShapesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/shapes': typeof ShapesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patterns' | '/shapes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patterns' | '/shapes'
  id: '__root__' | '/' | '/patterns' | '/shapes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatternsRoute: typeof PatternsRoute
  ShapesRoute: typeof ShapesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shapes': {
      id: '/shapes'
      path: '/shapes'
      fullPath: '/shapes'
      preLoaderRoute: typeof ShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatternsRoute: PatternsRoute,
  ShapesRoute: ShapesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
